export const groups = [
  {
    name: 'Portfolio sections',
    items: [
      ['hero', 'Hero', '✦'],
      ['about', 'About me', '◉'],
      ['skills', 'Skills', '⌁'],
      ['services', 'Services', '◆'],
      ['experience', 'Experience', '↗'],
      ['education', 'Education', '◇'],
      ['projects', 'Projects', '▦'],
      ['projectCard', 'Project card', '▣'],
      ['portfolioGallery', 'Portfolio gallery', '▧'],
      ['testimonials', 'Testimonials', '❞'],
      ['certifications', 'Certifications', '✓'],
      ['awards', 'Awards', '★'],
      ['resume', 'Resume download', '⇩'],
      ['contact', 'Contact', '✉'],
      ['footer', 'Footer', '▬'],
      ['faq', 'FAQ', '?'],
      ['cta', 'Call to action', '→'],
      ['statistics', 'Statistics', '123'],
      ['timeline', 'Timeline', '⋮'],
      ['logoGrid', 'Logo grid', '◫'],
    ],
  },
  {
    name: 'Layout',
    items: [
      ['section', 'Section', '□'],
      ['container', 'Container', '▭'],
      ['columns', 'Columns', 'Ⅱ'],
      ['grid', 'Grid', '▦'],
      ['spacer', 'Spacer', '↕'],
      ['divider', 'Divider', '—'],
    ],
  },
  {
    name: 'Content',
    items: [
      ['heading', 'Heading', 'H'],
      ['text', 'Text', '¶'],
      ['richText', 'Rich text', '¶+'],
      ['quote', 'Quote', '❞'],
      ['list', 'List', '☷'],
    ],
  },
  {
    name: 'Media & actions',
    items: [
      ['image', 'Image', '▧'],
      ['avatar', 'Profile image', '●'],
      ['gallery', 'Image gallery', '▦'],
      ['video', 'Video', '▶'],
      ['icon', 'Icon', '✦'],
      ['button', 'Button', '▰'],
      ['link', 'Link', '↗'],
      ['social', 'Social links', '◎'],
      ['navbar', 'Navbar', '☰'],
      ['brand', 'Logo / brand', 'P'],
      ['navLinks', 'Navigation links', '≡'],
      ['contactForm', 'Contact form', '✉'],
    ],
  },
];
